/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sister;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;

/**
 *
 * @author zhuxiaoyu
 */
public class QuizMenu extends javax.swing.JFrame {
    private MainMenu newMainMenu;
    private ArrayList<Question> questionData;
    private int currentIndex=0;
    private int total;
    /**
     * Creates new form QuizMenu
     */
    public QuizMenu() {
        initComponents();
        setContent(questionData.get(currentIndex));
        total=questionData.size();
        totalQuestion.setText(total+1+"");
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                exitOption(windowEvent);
                
            }
            
        });
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }
    
    public QuizMenu(MainMenu mainmenu,ArrayList<Question> questionData){
        this.newMainMenu=mainmenu;
        this.questionData=questionData;
    }
    
    public void exitOption(java.awt.event.WindowEvent windowEvent){
        boolean exitComfirm=JOptionPane.showConfirmDialog(null, 
                "Are you sure you want to close this window?", "Close Window?", 
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION;
        
        if (exitComfirm){
            this.dispose();
            newMainMenu.setVisible(true);
        }
    }
    
    public void storeMainMenu(MainMenu menu){
        this.newMainMenu=menu;
    }
    
    public void setContent(Question q){
        questionContent.setText(q.getContent());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selections = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        questionContent = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        selectionA = new javax.swing.JRadioButton();
        selectionB = new javax.swing.JRadioButton();
        selectionC = new javax.swing.JRadioButton();
        selectionD = new javax.swing.JRadioButton();
        selectionE = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        nextQuestion = new javax.swing.JButton();
        lastQuestion = new javax.swing.JButton();
        questionIndexInput = new javax.swing.JTextField();
        totalQuestion = new javax.swing.JLabel();
        submitAnswer = new javax.swing.JButton();
        saveAnswer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 400));

        questionContent.setBackground(new java.awt.Color(238, 238, 238));
        questionContent.setColumns(20);
        questionContent.setRows(5);
        questionContent.setText("1.");
        questionContent.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        questionContent.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        questionContent.setEnabled(false);
        jScrollPane1.setViewportView(questionContent);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        selections.add(selectionA);
        selectionA.setText("jRadioButton1");
        selectionA.setActionCommand("jRadioBu \ntton1");

        selections.add(selectionB);
        selectionB.setText("jRadioButton2");

        selections.add(selectionC);
        selectionC.setText("jRadioButton3");

        selections.add(selectionD);
        selectionD.setText("jRadioButton4");

        selections.add(selectionE);
        selectionE.setText("jRadioButton5");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectionA)
                    .addComponent(selectionB)
                    .addComponent(selectionC)
                    .addComponent(selectionD)
                    .addComponent(selectionE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(selectionA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectionB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectionC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectionD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectionE))
        );

        nextQuestion.setText(">");
        nextQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextQuestionActionPerformed(evt);
            }
        });

        lastQuestion.setText("<");
        lastQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastQuestionActionPerformed(evt);
            }
        });

        questionIndexInput.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        questionIndexInput.setText("1");
        questionIndexInput.setPreferredSize(new java.awt.Dimension(18, 28));

        totalQuestion.setText("/10");

        submitAnswer.setText("submit");

        saveAnswer.setText("save");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lastQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(questionIndexInput, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(totalQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nextQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addComponent(saveAnswer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submitAnswer))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lastQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(questionIndexInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(nextQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totalQuestion)
                .addComponent(submitAnswer)
                .addComponent(saveAnswer))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextQuestionActionPerformed
        // TODO add your handling code here:
        if(currentIndex==total-1){
            
        }
        else{
            currentIndex++;
            setContent(questionData.get(currentIndex));
        }
    }//GEN-LAST:event_nextQuestionActionPerformed

    private void lastQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastQuestionActionPerformed
        // TODO add your handling code here:
        if(currentIndex==0){
            
        }
        else{
            currentIndex--;
            setContent(questionData.get(currentIndex));
        }
    }//GEN-LAST:event_lastQuestionActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lastQuestion;
    private javax.swing.JButton nextQuestion;
    private javax.swing.JTextArea questionContent;
    private javax.swing.JTextField questionIndexInput;
    private javax.swing.JButton saveAnswer;
    private javax.swing.JRadioButton selectionA;
    private javax.swing.JRadioButton selectionB;
    private javax.swing.JRadioButton selectionC;
    private javax.swing.JRadioButton selectionD;
    private javax.swing.JRadioButton selectionE;
    private javax.swing.ButtonGroup selections;
    private javax.swing.JButton submitAnswer;
    private javax.swing.JLabel totalQuestion;
    // End of variables declaration//GEN-END:variables
}
